# Fly.io Configuration
app = "pharmacy-finder-chile"
primary_region = "mia"  # Miami - good for Latin America

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  APP_NAME = "Farmacias Chile"
  ENV = "production"
  PORT = "8080"
  
  # Database
  DATABASE_URL = "./pharmacy_finder.db"
  
  # API Configuration
  MINSAL_API_BASE = "https://midas.minsal.cl/farmacia_v2/WS"
  HTTP_TIMEOUT = "10.0"
  
  # Cache
  CACHE_TTL = "300"
  CACHE_HEALTH_CHECK_INTERVAL = "60"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

  # Health check
  [http_service.checks]
    [http_service.checks.alive]
      type = "http"
      interval = 30000
      timeout = 5000
      path = "/health"

[[services.ports]]
  port = 80
  handlers = ["http"]
  force_https = true

[[services.ports]]
  port = 443
  handlers = ["tls", "http"]

# Resource allocation
[resource]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

# Restart policy
[restart_policy]
  policy = "on-failure"

# Volume for persistent data (optional)
# [mounts]
# source = "pharmacy_data"
# destination = "/app/data"
